name: gitbook
on:
  push:
    branches:
      - master
jobs:
  gitbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PASSWORD }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Installing GitBook CLI'
      run: npm install -g gitbook-cli
    - name: 'Generating GitBook'
      run: |
        gitbook install
        gitbook build
        git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/manorrock/website
        cd website
        mkdir -p book/off-you-go-with-java || true
        cd book/off-you-go-with-java
        rm -rf *
        mv ../../../_book/* .
        ls 
        git config user.email "noreply@manorrock.com"
        git config user.name "Automated process"
        git add .
        git commit -m "Publishing Book"
        git push
